<a href="https://colab.research.google.com/github/malharinamdar/TechRush-2024/blob/main/diabetes_gemini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q -U google-generativeai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.2/164.2 kB 1.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 718.3/718.3 kB 8.0 MB/s eta 0:00:00


In [2]:
import google.generativeai as genai

In [3]:
genai.configure(api_key="api-key")

In [4]:
MODEL_CONFIG = {
  "temperature": 0.2,
  "top_p": 1,
  "top_k": 32,
  "max_output_tokens": 4096,
}

## Safety Settings of Model
safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  }
]

In [5]:
model = genai.GenerativeModel('gemini-1.5-flash')

In [6]:
import pickle
import pandas as pd



update_model = pickle.load(open('/content/trained_model.pkl', 'rb'))  # Replace 'model.pkl' with your model file

custom_data = [["Male", 45.0, 0, 0, "non-smoker", 25.6, 6.5, 110]]

custom_df = pd.DataFrame(custom_data, columns=['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level'])
predictions = update_model.predict(custom_df)
print(predictions)




[0]


In [7]:
custom_data = [["Male", 45.0, 0, 0, "non-smoker", 25.6, 6.5, 110]]

custom_df = pd.DataFrame(custom_data, columns=['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level'])
predictions = update_model.predict(custom_df)
print(predictions)

[0]


In [8]:
prompt_context = f"""
You are a helpful health advisor.
A predictive model has been used to assess a patient's health risks.
Here are the patient's details and the model's prediction:

Patient Details:
Gender: {custom_df['gender'][0]}
Age: {custom_df['age'][0]}
Hypertension: {'Yes' if custom_df['hypertension'][0] == 1 else 'No'}
Heart Disease: {'Yes' if custom_df['heart_disease'][0] == 1 else 'No'}
Smoking History: {custom_df['smoking_history'][0]}
BMI: {custom_df['bmi'][0]}
HbA1c Level: {custom_df['HbA1c_level'][0]}
Blood Glucose Level: {custom_df['blood_glucose_level'][0]}

Model Prediction:
Risk of developing diabetes: {'High' if predictions[0] == 1 else 'Low'}

Please provide personalized guidance to the patient.
Focus on the specific parameters that might be contributing to their risk, and offer actionable advice for improvement.
"""


response = model.generate_content(prompt_context)


In [9]:
response.text

"##  Personalized Guidance on Your Diabetes Risk\n\nHi there, based on your details and the model's prediction, you have a low risk of developing diabetes. That's great news! However, it's important to remember that this is a prediction and not a guarantee. \n\nHere's a closer look at your current health markers and what they mean:\n\n* **HbA1c Level:**  Your HbA1c level of 6.5 falls within the pre-diabetes range (5.7-6.4 is considered normal). This indicates that your blood sugar levels have been slightly elevated over the past few months.  While this is not a diagnosis of diabetes, it is important to be aware and take steps to manage your blood sugar.\n* **Blood Glucose Level:** Your blood glucose level of 110 is also slightly elevated. A fasting blood glucose level between 70-99 is considered normal. \n* **BMI:** Your BMI of 25.6 falls within the overweight category. While this is not directly related to diabetes, it can increase your risk. \n\n**Actionable Advice for Improvement:**

In [10]:
## Output below

## Personalized Health Guidance

Hi there, based on your details and the predictive model, your risk of developing diabetes is currently low. That's great news! However, it's important to understand that this is just a snapshot in time and your risk can change.  

Let's look at your specific details:

* **HbA1c Level (6.5):** This is slightly elevated and indicates that your average blood sugar levels have been higher than optimal in recent months. While this doesn't necessarily mean you have diabetes, it's a good indicator that you need to pay attention to your blood sugar control.
* **Blood Glucose Level (110):** This level is also on the higher end of the normal range.
* **BMI (25.6):** You're currently in the overweight category. Maintaining a healthy weight is crucial for overall health and managing blood sugar levels.

**Here's what you can do to further reduce your risk of developing diabetes:**

* **Monitor Your Blood Sugar:**  Talk to your doctor about getting regular blood sugar checks, especially if you have any family history of diabetes. This will help identify any potential issues early on.
* **Maintain a Healthy Weight:**  Even a small amount of weight loss can significantly improve your blood sugar control. Aim for a gradual and sustainable weight loss program through healthy diet and regular exercise.
* **Eat a Balanced Diet:** Focus on whole, unprocessed foods like fruits, vegetables, lean protein, and whole grains. Limit sugary drinks, processed foods, and saturated and trans fats.
* **Get Regular Exercise:** Aim for at least 150 minutes of moderate-intensity aerobic activity or 75 minutes of vigorous-intensity aerobic activity per week.
* **Manage Stress:** Stress can impact blood sugar levels.  Find healthy ways to manage stress like yoga, meditation, or spending time in nature.

**Remember, maintaining a healthy lifestyle is key to preventing diabetes and maintaining overall well-being. It's important to discuss any concerns you have with your doctor and work together to develop a personalized plan that addresses your individual needs.**

**Don't hesitate to ask your doctor about further testing or guidance if you have any concerns.**
